# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
logger:
  default: warning
  logs:
    # homeassistant.components.nest: debug
    # homeassistant.components.nest.climate_sdm: debug
    # homeassistant.components.nest.camera_sdm: debug
    # homeassistant.components.nest.sensor_sdm: debug
    # google_nest_sdm: debug
    # google_nest_sdm.device: debug
    # google_nest_sdm.device_manager: debug
    # google_nest_sdm.google_nest_subscriber: debug
    # google_nest_sdm.event: debug
    # google.cloud.pubsub_v1: debug
    # google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager: debug
    homeassistant.components.velux: debug
    pyvlx: debug
stream:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages
  time_zone: Europe/Brussels
  external_url: !secret external_url
  internal_url: "http://192.168.1.5:8123"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        #192.168.1.229: 1cf3f6c6c4d844ec9ed5e0c004551dbf
        192.168.1.21: d4f3b2e207d94448b27eb8dcd1ede3ef
      allow_bypass_login: true
    - type: homeassistant
# Example configuration.yaml entry
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: "3360"
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
lovelace:
  mode: storage
# Example configuration.yaml entry
media_extractor:
# Text to speech
tts:
  - platform: google_translate
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_id
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Lotte
frontend:
  themes: !include_dir_merge_named themes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include_dir_merge_list binary_sensors

browser_mod:
  prefix: "browser_"
  devices:
    d04d32b8-c78a54f6:
      name: kitchendash
influxdb:
  host: !secret influxdb_host
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
recorder:
  db_url: !secret recorder_db_url

velux:
  host: !secret velux_host
  password: !secret velux_password

light:
  - platform: flux_led
    automatic_add: true
sensor:
  - platform: history_stats
    name: Quarantine meter Jurgen
    entity_id: person.jurgen_coetsiers
    state: "home"
    type: ratio
    duration:
      days: 14
    end: "{{ now() }}"

  - platform: history_stats
    name: Quarantine meter Kristel
    entity_id: person.kristel_bekaert
    state: "home"
    type: ratio
    duration:
      days: 14
    end: "{{ now() }}"

  - platform: history_stats
    name: Quarantine meter Jurgen weggeweest
    entity_id: person.jurgen_coetsiers
    state: "home"
    type: count
    duration:
      days: 14
    end: "{{ now() }}"

  - platform: history_stats
    name: Quarantine meter Kistel weggeweest
    entity_id: person.kristel_bekaert
    state: "home"
    type: count
    duration:
      days: 14
    end: "{{ now() }}"

  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
cover:
  - platform: group
    name: Rolluiken Slaapkamer Boven
    entities:
      - cover.rolluik_tuin_1
      - cover.rolluik_straat_1
      - cover.rolluik_straat_2
      - cover.rolluik_straat_3
      - cover.rolluik_tuin_2
      - cover.rolluik_straat_4


spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  accounts:
    kristel:
      sp_dc: !secret kristel_sp_dc
      sp_key: !secret kristel_sp_key
nest:
  client_id: 83751842865-bbgsu1tg1dnq9vpl7vd6i4s4t003okok.apps.googleusercontent.com
  client_secret: 4WpiF64SDrDCXuXzJv0UrVjH
  # "Project ID" in the Device Access Console
  project_id: 02a0314d-46f0-497a-bd84-2146cd5b751c
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: projects/home-assistant-308010/subscriptions/Pastorale
