- platform: yr
- platform: mqtt
  name: "Basement Temperature"
  state_topic: "tele/basement/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  unit_of_measurement: "째C"
- platform: mqtt
  name: "Basement Humidity"
  state_topic: "tele/basement/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "tele/verwarming/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  unit_of_measurement: "째C"
- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "tele/verwarming/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  unit_of_measurement: "%"
# - platform: plex
# - platform: cups
#   printers:
#     - Brother_MFC_J5720DW
#   host: 192.168.50.129
# Current Time and Date
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: wunderground
  api_key: !secret wunderground_key
  pws_id: !secret wunderground_pws
  lang: 'NL'
  monitored_conditions:
    - weather
    - feelslike_c
    - temp_c
    - relative_humidity
- platform: waze_travel_time
  origin: Ninovesteenweg 206, 9320 Erembodegem
  destination: Meelfabrieksplein 10, 1080 Sint-Jans Molenbeek
  name: Office Travel Time
  region: 'EU'
- platform: waze_travel_time
  origin: Ninovesteenweg 206, 9320 Erembodegem
  destination: Kloosterstraat, Mere
  name: SJS Travel Time
  region: 'EU'
- platform: waze_travel_time
  origin: Ninovesteenweg 206, 9320 Erembodegem
  destination: Dom Modest Van Asschelaan 22, 9320 Erembodegem 
  name: De Stip Travel Time
  region: 'EU'
- platform: template
  sensors:
    next_pmd:
      value_template: "{{ states.calendar.PMD.attributes.start_time }}"
      friendly_name: "PMD"
- platform: template
  sensors:
    next_gft:
      value_template: "{{ states.calendar.GFT.attributes.start_time }}"
      friendly_name: "GFT"
- platform: template
  sensors:
    next_huisvuil:
      value_template: "{{ states.calendar.Huisvuil.attributes.start_time }}"
      friendly_name: "Huisvuil"
      icon_template: mdi:delete
- platform: template
  sensors:
    next_papier:
      value_template: "{{ states.calendar.Papier.attributes.start_time }}"
      friendly_name: "Papier"
      icon_template: mdi:newspaper

- platform: template
  sensors:
    next_glas:
      value_template: "{{ states.calendar.Glas.attributes.start_time }}"
      friendly_name: "Glas"
      icon_template: mdi:bottle-wine
- platform: mqtt
  name: "Garage Temperature"
  state_topic: "tele/switchboard/SENSOR"
  value_template: "{{ value_json['DHT11'].Temperature }}"
  unit_of_measurement: "째C"
- platform: mqtt
  name: "Garage Humidity"
  state_topic: "tele/switchboard/SENSOR"
  value_template: "{{ value_json['DHT11'].Humidity }}"
  unit_of_measurement: "째C"
- platform: template
  sensors:
    james_status:
      value_template: "{{ states.vacuum.james.attributes.status }}"
      friendly_name: "Status"

- platform: template
  sensors:
    james_:
      value_template: "{{ states.vacuum.james.attributes.battery_level }}"
      friendly_name: "Battery Level"      
      icon_template: "{{ states.vacuum.james.attributes.battery_icon }}"
- platform: buienradar
  name: Erembodegem
  monitored_conditions:
    - stationname
    - conditioncode
    - condition
    - conditiondetailed
    - conditionexact
    - symbol
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total
- platform: atagone
  host: 192.168.50.65
  port: 10000
  scan_interval: 10
  resources:
    - room_temp
    - outside_temp
    - avg_outside_temp
    - pcb_temp
    - ch_setpoint
    - ch_water_pressure
    - ch_water_temp
    - ch_return_temp
    - dhw_water_temp
    - dhw_water_pres
    - boiler_status
    - boiler_config