#!/usr/bin/env sh
# xset -dpms
#xset s off
#xset s noblank

unclutter &
chromium-browser http://homeassistant.local:8123/dwains-dashboard/home \
  --window-size=1920,1080 \
  --window-position=0,0 \
  --start-fullscreen \
  --kiosk \
  --noerrdialogs \
  --disable-translate \
  --no-first-run \
  --fast \
  --fast-start \
  --disable-infobars \
  --disable-features=TranslateUI \
  --disk-cache-dir=/tmp \
  --overscroll-history-navigation=0 \
  --disable-pinch \
#  --ignore-certificate-errors
#  --incognito \
